### ISSUE TITLE
How to specify both attr and content?

### ISSUE THREAD

**Issue by szhu** [arch-js/dom#1]
Really basic simple (and probably stupid) question, but I can't it documented anywhere. How do I make something like this using `arch.DOM.a`?

``` html
<a href="myurl">my text</a>
```

All the examples given pass either an attributes object or contents string/list to `arch.DOM.a`, but never both. I tried the React convention of using the `children` prop, but that didn't work either.

**Comment by charypar** [comment]
you should be able to call it like the original React factories, i.e.

``` js
a({ href: 'myurl' }, 'my text')
```

**Comment by szhu** [comment]
Ah, that works. Always used JSX so I never knew what the original methods looked like :)
